export const ADD_USER_STARTED = 'ADD_USER_STARTED';
export const ADD_USER_COMPLETED = 'ADD_USER_COMPLETED';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';

export const FETCH_USERS_STARTED = 'FETCH_USERS_STARTED';
export const FETCH_USERS_COMPLETED = 'FETCH_USERS_COMPLETED';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';


export const FETCH_EMPLOYEES_STARTED = 'FETCH_EMPLOYEES_STARTED';
export const FETCH_EMPLOYEES_COMPLETED = 'FETCH_EMPLOYEES_COMPLETED';
export const FETCH_EMPLOYEES_ERROR  = 'FETCH_EMPLOYEES_ERROR';

export const ADD_EMPLOYEE_STARTED = 'ADD_EMPLOYEE_STARTED';
export const ADD_EMPLOYEE_COMPLETED = 'ADD_EMPLOYEE_COMPLETED';
export const ADD_EMPLOYEE_ERROR = 'ADD_EMPLOYEE_ERROR';

export const ADD_IMAGE_STARTED = 'ADD_IMAGE_STARTED';
export const ADD_IMAGE_COMPLETED = 'ADD_IMAGE_COMPLETED';
export const ADD_IMAGE_ERROR = 'ADD_IMAGE_ERROR';
